import React, { Component } from 'react';

class News extends Component {
    render() {
        return (
            <div>
                <div className="post-list">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-10 col-md-offset-1">
                                <legend> <span><i className="fa fa-caret-right" aria-hidden="true" /> Tin Tức BDS <i className="fa fa-caret-left" aria-hidden="true" /></span></legend>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../chu-dau-tu-du-an-cong-hoa-garden/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/07/phoi-canh-cong-hoa-garden-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../chu-dau-tu-du-an-cong-hoa-garden/index.html" rel="bookmark">Nói về Chủ đầu tư dự án Cộng Hòa Garden?</a></h3>
                                        <p>Chủ đâu tư của dự án khu căn hộ Cộng Hòa Garden là ai? Đánh giá sự ảnh hưởng thời hạn sử dụng 42 năm tới bài toán về hiệu quả khai thác bất động sản. Có nên mua dự án Cộng Hòa Garden? Chủ đầu tư Cộng Hòa Garden? […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/chu-dau-tu-du-an-cong-hoa-garden/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/chu-dau-tu-du-an-cong-hoa-garden/%20-%20N%c3%b3i%20v%e1%bb%81%20Ch%e1%bb%a7%20%c4%91%e1%ba%a7u%20t%c6%b0%20d%e1%bb%b1%20%c3%a1n%20C%e1%bb%99ng%20H%c3%b2a%20Garden?"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/chu-dau-tu-du-an-cong-hoa-garden/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/chu-dau-tu-du-an-cong-hoa-garden/&media=https://giahungland.vn/wp-content/uploads/2018/07/phoi-canh-cong-hoa-garden.jpg&description=N%c3%b3i%20v%e1%bb%81%20Ch%e1%bb%a7%20%c4%91%e1%ba%a7u%20t%c6%b0%20d%e1%bb%b1%20%c3%a1n%20C%e1%bb%99ng%20H%c3%b2a%20Garden?"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../chu-dau-tu-du-an-cong-hoa-garden/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../can-ho-binh-riverside/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/05/can-ho-binh-an-riverside-ha-do-quan-8-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../can-ho-binh-riverside/index.html" rel="bookmark">Thông tin căn hộ Bình An Riverside tại quận 8 của tập đoàn Hà Đô</a></h3>
                                        <p>Dự án Bình An Riverside Phạm Thế Hiển, Quận 8 là khu căn hộ cao cấp thuộc tập đoàn Hà Đô, một đơn vị nhiều uy tín và kinh nghiệm trong lĩnh vực phát triển các dự án bất động sản như Hà Đô Nguyễn Văn Công, Hà Đô Centrosa […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/can-ho-binh-riverside/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/can-ho-binh-riverside/%20-%20Th%c3%b4ng%20tin%20c%c4%83n%20h%e1%bb%99%20B%c3%acnh%20An%20Riverside%20t%e1%ba%a1i%20qu%e1%ba%adn%208%20c%e1%bb%a7a%20t%e1%ba%adp%20%c4%91o%c3%a0n%20H%c3%a0%20%c4%90%c3%b4"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/can-ho-binh-riverside/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/can-ho-binh-riverside/&media=https://giahungland.vn/wp-content/uploads/2018/05/can-ho-binh-an-riverside-ha-do-quan-8.jpg&description=Th%c3%b4ng%20tin%20c%c4%83n%20h%e1%bb%99%20B%c3%acnh%20An%20Riverside%20t%e1%ba%a1i%20qu%e1%ba%adn%208%20c%e1%bb%a7a%20t%e1%ba%adp%20%c4%91o%c3%a0n%20H%c3%a0%20%c4%90%c3%b4"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../can-ho-binh-riverside/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2017/07/gia-hung-land-2-12-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/index.html" rel="bookmark">Tuyển dụng nhân viên kinh doanh bất động sản</a></h3>
                                        <p>Công ty TNHH đầu tư địa ốc Gia Hưng cần tuyển dụng gấp : – 50 Nhân viên kinh doanh BĐS. Mô tả công việc Tìm kiếm, mở rộng mối quan hệ khách hàng. Khai thác nhu cầu và tư vấn khách hàng chọn mua các sản phẩm, dịch vụ […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/%20-%20Tuy%e1%bb%83n%20d%e1%bb%a5ng%20nh%c3%a2n%20vi%c3%aan%20kinh%20doanh%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/&media=https://giahungland.vn/wp-content/uploads/2017/07/gia-hung-land-2-12.jpg&description=Tuy%e1%bb%83n%20d%e1%bb%a5ng%20nh%c3%a2n%20vi%c3%aan%20kinh%20doanh%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../tuyen-dung-nhan-vien-kinh-doanh-bat-dong-san/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../mua-ban-cac-can-ho-tra-gop/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/02/ban-can-ho-tra-gop-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../mua-ban-cac-can-ho-tra-gop/index.html" rel="bookmark">Hướng dẫn mua bán căn hộ trả góp tại TP.HCM</a></h3>
                                        <p>Với nhau cầu nhà ở tăng cao thì nhu cầu mua bán các căn hộ trả góp, chung cư trả góp đang được rất nhiều người quan tâm. Đáng mừng là hiện nay, việc mua một căn hộ khá dễ dàng do nhà nước, ngân hàng đang có các chính […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/mua-ban-cac-can-ho-tra-gop/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/mua-ban-cac-can-ho-tra-gop/%20-%20H%c6%b0%e1%bb%9bng%20d%e1%ba%abn%20mua%20b%c3%a1n%20c%c4%83n%20h%e1%bb%99%20tr%e1%ba%a3%20g%c3%b3p%20t%e1%ba%a1i%20TP.HCM"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/mua-ban-cac-can-ho-tra-gop/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/mua-ban-cac-can-ho-tra-gop/&media=https://giahungland.vn/wp-content/uploads/2018/02/ban-can-ho-tra-gop.jpg&description=H%c6%b0%e1%bb%9bng%20d%e1%ba%abn%20mua%20b%c3%a1n%20c%c4%83n%20h%e1%bb%99%20tr%e1%ba%a3%20g%c3%b3p%20t%e1%ba%a1i%20TP.HCM"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../mua-ban-cac-can-ho-tra-gop/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../du-duong-vanh-dai-3-tp-hcm/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/01/quy-hoach-duong-vanh-dai-3-tphcm-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../du-duong-vanh-dai-3-tp-hcm/index.html" rel="bookmark">đường vành đai 3 tp.hcm sẽ thay đổi thị trường bất động sản vùng ven</a></h3>
                                        <p>Dự án đường vành đai 3 tphcm vừa được bộ giao thông vận tải TP.HCM trình duyệt thủ tướng chính phủ. Dự án này sẽ rút ngắn đáng kể khoảng cánh và thời gian liên kết vùng giữa Long An, Bình Chánh, Hooc Môn, Bình Dương, Nhơn Trạch- Đồng Nai. […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/du-duong-vanh-dai-3-tp-hcm/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/du-duong-vanh-dai-3-tp-hcm/%20-%20%c4%91%c6%b0%e1%bb%9dng%20v%c3%a0nh%20%c4%91ai%203%20tp.hcm%20s%e1%ba%bd%20thay%20%c4%91%e1%bb%95i%20th%e1%bb%8b%20tr%c6%b0%e1%bb%9dng%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20v%c3%b9ng%20ven"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/du-duong-vanh-dai-3-tp-hcm/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/du-duong-vanh-dai-3-tp-hcm/&media=https://giahungland.vn/wp-content/uploads/2018/01/quy-hoach-duong-vanh-dai-3-tphcm.jpg&description=%c4%91%c6%b0%e1%bb%9dng%20v%c3%a0nh%20%c4%91ai%203%20tp.hcm%20s%e1%ba%bd%20thay%20%c4%91%e1%bb%95i%20th%e1%bb%8b%20tr%c6%b0%e1%bb%9dng%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20v%c3%b9ng%20ven"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../du-duong-vanh-dai-3-tp-hcm/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../nha-o-xa-hoi-la-gi/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2017/09/du-an-callagarden-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../nha-o-xa-hoi-la-gi/index.html" rel="bookmark">Nhà ở xã hội là gì? tìm hiểu các vấn đề trước khi mua bán</a></h3>
                                        <p>Nhà ở xã hội là gì? có mua bán được không ? sở hữu bao nhiêu năm hay quy định và những ưu điểm của nó so với nhà ở thương mại là các câu hỏi thường gặp khi khách hàng tìm mua một dự án nhà ở xã hội. […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/nha-o-xa-hoi-la-gi/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/nha-o-xa-hoi-la-gi/%20-%20Nh%c3%a0%20%e1%bb%9f%20x%c3%a3%20h%e1%bb%99i%20l%c3%a0%20g%c3%ac?%20t%c3%acm%20hi%e1%bb%83u%20c%c3%a1c%20v%e1%ba%a5n%20%c4%91%e1%bb%81%20tr%c6%b0%e1%bb%9bc%20khi%20mua%20b%c3%a1n"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/nha-o-xa-hoi-la-gi/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/nha-o-xa-hoi-la-gi/&media=https://giahungland.vn/wp-content/uploads/2017/09/du-an-callagarden.jpg&description=Nh%c3%a0%20%e1%bb%9f%20x%c3%a3%20h%e1%bb%99i%20l%c3%a0%20g%c3%ac?%20t%c3%acm%20hi%e1%bb%83u%20c%c3%a1c%20v%e1%ba%a5n%20%c4%91%e1%bb%81%20tr%c6%b0%e1%bb%9bc%20khi%20mua%20b%c3%a1n"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../nha-o-xa-hoi-la-gi/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../tap-doan-hoa-lam/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/01/tap-doan-hoa-lam-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../tap-doan-hoa-lam/index.html" rel="bookmark">Tập đoàn Hoa Lâm, chủ đầu tư của nhiều dự án bất động sản triệu đô</a></h3>
                                        <p>Tập đoàn Hoa Lâm hay chủ đầu tư Hoa Lâm là cái tên được tìm kiếm nhiều nhất sau khi King Dom 101 – một dự án bất động sản thuộc phân khúc cao cấp được triển khai chào bán vào cuối 2018 được thị trường bất động sản đón […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/tap-doan-hoa-lam/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/tap-doan-hoa-lam/%20-%20T%e1%ba%adp%20%c4%91o%c3%a0n%20Hoa%20L%c3%a2m,%20ch%e1%bb%a7%20%c4%91%e1%ba%a7u%20t%c6%b0%20c%e1%bb%a7a%20nhi%e1%bb%81u%20d%e1%bb%b1%20%c3%a1n%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20tri%e1%bb%87u%20%c4%91%c3%b4"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/tap-doan-hoa-lam/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/tap-doan-hoa-lam/&media=https://giahungland.vn/wp-content/uploads/2018/01/tap-doan-hoa-lam.jpg&description=T%e1%ba%adp%20%c4%91o%c3%a0n%20Hoa%20L%c3%a2m,%20ch%e1%bb%a7%20%c4%91%e1%ba%a7u%20t%c6%b0%20c%e1%bb%a7a%20nhi%e1%bb%81u%20d%e1%bb%b1%20%c3%a1n%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20tri%e1%bb%87u%20%c4%91%c3%b4"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../tap-doan-hoa-lam/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../du-an-west-intela-tai-quan-8/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/01/nha-mau-du-an-west-intela-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../du-an-west-intela-tai-quan-8/index.html" rel="bookmark">Những ưu điểm của dự án west intela tại quận 8</a></h3>
                                        <p>Dự án west intela là khu căn hộ phân khúc tầm trung do LDG làm chủ đầu tư. Đây tiếp tục là dự án căn hộ thứ 3 liên tiếp của LDG lấy cảm hứng từ những tòa nhà thông minh từ các nước tiên tiếng trên thế giới như […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/du-an-west-intela-tai-quan-8/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/du-an-west-intela-tai-quan-8/%20-%20Nh%e1%bb%afng%20%c6%b0u%20%c4%91i%e1%bb%83m%20c%e1%bb%a7a%20d%e1%bb%b1%20%c3%a1n%20west%20intela%20t%e1%ba%a1i%20qu%e1%ba%adn%208"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/du-an-west-intela-tai-quan-8/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/du-an-west-intela-tai-quan-8/&media=https://giahungland.vn/wp-content/uploads/2018/01/nha-mau-du-an-west-intela.jpg&description=Nh%e1%bb%afng%20%c6%b0u%20%c4%91i%e1%bb%83m%20c%e1%bb%a7a%20d%e1%bb%b1%20%c3%a1n%20west%20intela%20t%e1%ba%a1i%20qu%e1%ba%adn%208"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../du-an-west-intela-tai-quan-8/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../co-nen-vay-tien-mua-nha/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/01/co-nen-vay-tien-ngan-hang-mua-nha-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../co-nen-vay-tien-mua-nha/index.html" rel="bookmark">Có nên vay tiền ngân hàng mua nhà, căn hộ không? – kinh nghiệm</a></h3>
                                        <p>Có nên vay tiền ngân hàng để mua nhà hay căn hộ không? đây là một câu hỏi khá nhiều người đặt ra khi thị trường bất động sản hiện nay đang rất sối động. Giá của nhà đất lẫn căn hộ tăng lên từng ngày mà tiền tích lũy […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/co-nen-vay-tien-mua-nha/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/co-nen-vay-tien-mua-nha/%20-%20C%c3%b3%20n%c3%aan%20vay%20ti%e1%bb%81n%20ng%c3%a2n%20h%c3%a0ng%20mua%20nh%c3%a0,%20c%c4%83n%20h%e1%bb%99%20kh%c3%b4ng?%20%e2%80%93%20kinh%20nghi%e1%bb%87m"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/co-nen-vay-tien-mua-nha/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/co-nen-vay-tien-mua-nha/&media=https://giahungland.vn/wp-content/uploads/2018/01/co-nen-vay-tien-ngan-hang-mua-nha.jpg&description=C%c3%b3%20n%c3%aan%20vay%20ti%e1%bb%81n%20ng%c3%a2n%20h%c3%a0ng%20mua%20nh%c3%a0,%20c%c4%83n%20h%e1%bb%99%20kh%c3%b4ng?%20%e2%80%93%20kinh%20nghi%e1%bb%87m"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../co-nen-vay-tien-mua-nha/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../bat-dong-san-quan-9/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2018/01/bat-dong-san-quan-9-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../bat-dong-san-quan-9/index.html" rel="bookmark">Giá trị thật của Bất động sản quận 9 đang ở đâu trước cơn bão giá?</a></h3>
                                        <p>Bất động sản quận 9 hiện đang có dấu hiệu chững lại, các giao dịch dần đã giảm nhiệt. Các dự án mở ra thưa thớt và dân đầu tư cũng dần dần ít mặn mà. Liệu rằng thời điểm bây giờ, giá của bất động sản tại quận 9 […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/bat-dong-san-quan-9/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/bat-dong-san-quan-9/%20-%20Gi%c3%a1%20tr%e1%bb%8b%20th%e1%ba%adt%20c%e1%bb%a7a%20B%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20qu%e1%ba%adn%209%20%c4%91ang%20%e1%bb%9f%20%c4%91%c3%a2u%20tr%c6%b0%e1%bb%9bc%20c%c6%a1n%20b%c3%a3o%20gi%c3%a1?"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/bat-dong-san-quan-9/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/bat-dong-san-quan-9/&media=https://giahungland.vn/wp-content/uploads/2018/01/bat-dong-san-quan-9.jpg&description=Gi%c3%a1%20tr%e1%bb%8b%20th%e1%ba%adt%20c%e1%bb%a7a%20B%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20qu%e1%ba%adn%209%20%c4%91ang%20%e1%bb%9f%20%c4%91%c3%a2u%20tr%c6%b0%e1%bb%9bc%20c%c6%a1n%20b%c3%a3o%20gi%c3%a1?"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../bat-dong-san-quan-9/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../thap-86-tower/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2017/08/86-tower-empire-city-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../thap-86-tower/index.html" rel="bookmark">Tòa Tháp 86 Tower Empire City – công trình cao nhất việt nam</a></h3>
                                        <p>Tòa tháp 86 Tower là công trình biểu tưởng của dự án bất động sản cao cấp Empire City nằm tại mặt tiền mai chí thọ quận 2. Đây là công trình trung tâm, thể hiện sự xa hoa tráng lệ và đẳng cấp của khu phức hợp cao cấp […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/thap-86-tower/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/thap-86-tower/%20-%20T%c3%b2a%20Th%c3%a1p%2086%20Tower%20Empire%20City%20%e2%80%93%20c%c3%b4ng%20tr%c3%acnh%20cao%20nh%e1%ba%a5t%20vi%e1%bb%87t%20nam"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/thap-86-tower/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/thap-86-tower/&media=https://giahungland.vn/wp-content/uploads/2017/08/86-tower-empire-city.jpg&description=T%c3%b2a%20Th%c3%a1p%2086%20Tower%20Empire%20City%20%e2%80%93%20c%c3%b4ng%20tr%c3%acnh%20cao%20nh%e1%ba%a5t%20vi%e1%bb%87t%20nam"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../thap-86-tower/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="post-block media">
                                    <div className="media-left"> <a href="../tim-kiem-khach-hang-bat-dong-san/index.html" rel="bookmark"><img style={{ maxWidth: 210 }} className="media-object img-thumbnail" src="../wp-content/uploads/2017/08/cach-tim-kim-khach-hang-bat-dong-san-210x150.jpg" /></a></div>
                                    <div className="media-body"><h3><a href="../tim-kiem-khach-hang-bat-dong-san/index.html" rel="bookmark">Tìm kiếm khách hàng bất động sản chỉ với ngân sách từ 0 đồng</a></h3>
                                        <p>Tìm kiếm khách hàng là một trong những yếu tố quan trọng nhất dẫn đến sự thành công của một SALE bất động sản. Hôm nay mình sẽ viết một tài liệu có thể giúp BẠN tiếp cận được hàng ngàn KHÁCH HÀNG đang quan tâm bất động sản, và […]</p>
                                        <div className="social-loop" style={{ float: 'left', margin: 0 }}> <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://giahungland.vn/tim-kiem-khach-hang-bat-dong-san/"><i className="fa fa-facebook" aria-hidden="true" /></a> <a target="_blank" href="https://twitter.com/home?status=https://giahungland.vn/tim-kiem-khach-hang-bat-dong-san/%20-%20T%c3%acm%20ki%e1%ba%bfm%20kh%c3%a1ch%20h%c3%a0ng%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20ch%e1%bb%89%20v%e1%bb%9bi%20ng%c3%a2n%20s%c3%a1ch%20t%e1%bb%ab%200%20%c4%91%e1%bb%93ng"><i className="fa fa-twitter" aria-hidden="true" /></a> <a target="_blank" href="https://plus.google.com/share?url=https://giahungland.vn/tim-kiem-khach-hang-bat-dong-san/"><i className="fa fa-google-plus" aria-hidden="true" /></a> <a target="_blank" href="https://pinterest.com/pin/create/button/?url=https://giahungland.vn/tim-kiem-khach-hang-bat-dong-san/&media=https://giahungland.vn/wp-content/uploads/2017/08/cach-tim-kim-khach-hang-bat-dong-san.jpg&description=T%c3%acm%20ki%e1%ba%bfm%20kh%c3%a1ch%20h%c3%a0ng%20b%e1%ba%a5t%20%c4%91%e1%bb%99ng%20s%e1%ba%a3n%20ch%e1%bb%89%20v%e1%bb%9bi%20ng%c3%a2n%20s%c3%a1ch%20t%e1%bb%ab%200%20%c4%91%e1%bb%93ng"><i className="fa fa-pinterest" aria-hidden="true" /></a></div> <a href="../tim-kiem-khach-hang-bat-dong-san/index.html" rel="bookmark" title className="btn giahung-btn pull-right">Xem tiếp <i className="fa fa-arrow-right" aria-hidden="true" /></a></div>
                                </div>
                                <div className="clearfix" />
                                <div className="page-nav">
                                    <div className="pages clearfix">
                                        <ul className="pagination">
                                            <li className="paginated_link active"><span aria-current="page" className="page-numbers current">1</span></li>
                                            <li className="paginated_link"><a className="page-numbers" href="page/2/index.html">2</a></li>
                                            <li className="paginated_link"><a className="page-numbers" href="page/3/index.html">3</a></li>
                                            <li className="paginated_link"><span className="page-numbers dots">…</span></li>
                                            <li className="paginated_link"><a className="page-numbers" href="page/7/index.html">7</a></li>
                                            <li className="paginated_link"><a className="next page-numbers" href="page/2/index.html">»</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <section id="contact" className="contact" style={{ background: 'linear-gradient( rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url(../wp-content/uploads/2018/08/cropped-c-Michael-Sch%c3%bctz-fotolia.com_.jpg)', backgroundAttachment: 'fixed', backgroundSize: 'cover' }}>
                    <div className="container">
                        <div className="row">
                            <div className="col-sm-5">
                                <legend> Điền thông tin để nhận báo giá và tư vấn miễn phí</legend>
                            </div>
                            <div className="col-sm-7">
                                <div role="form" className="wpcf7" id="wpcf7-f1341-o1" lang="vi" dir="ltr">
                                    <div className="screen-reader-response" />
                                    <form action="https://giahungland.vn/tin-tuc-bds/#wpcf7-f1341-o1" method="post" className="wpcf7-form" noValidate="novalidate">
                                        <div style={{ display: 'none' }}> <input type="hidden" name="_wpcf7" defaultValue={1341} /> <input type="hidden" name="_wpcf7_version" defaultValue="5.0.3" /> <input type="hidden" name="_wpcf7_locale" defaultValue="vi" /> <input type="hidden" name="_wpcf7_unit_tag" defaultValue="wpcf7-f1341-o1" /> <input type="hidden" name="_wpcf7_container_post" defaultValue={0} /></div>
                                        <p><span className="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" defaultValue size={40} className="wpcf7-form-control wpcf7-text wpcf7-validates-as-required form-control" aria-required="true" aria-invalid="false" placeholder="Họ tên *" /></span></p>
                                        <div className="row" style={{ marginBottom: 10 }}>
                                            <div className="col-sm-6"> <span className="wpcf7-form-control-wrap your-phone"><input type="tel" name="your-phone" defaultValue size={40} className="wpcf7-form-control wpcf7-text wpcf7-tel wpcf7-validates-as-required wpcf7-validates-as-tel form-control" aria-required="true" aria-invalid="false" placeholder="Số điện thoại *" /></span></div>
                                            <div className="col-sm-6"> <span className="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" defaultValue size={40} className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-email form-control" aria-invalid="false" placeholder="Địa chỉ Email" /></span></div>
                                        </div>
                                        <p><span className="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols={40} rows={3} className="wpcf7-form-control wpcf7-textarea form-control" aria-invalid="false" placeholder="Nội dung" defaultValue={""} /></span></p>
                                        <p><input type="submit" defaultValue="Gửi đi" className="wpcf7-form-control wpcf7-submit btn-warning btn giahung-btn" /></p>
                                        <div className="wpcf7-response-output wpcf7-display-none" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        );
    }
}

export default News;